// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAje2eAHvAmROiYZdWp_snAAuIDn2_WAxQ',
    appId: '1:444912210132:web:5b6e088d49459c6353eb41',
    messagingSenderId: '444912210132',
    projectId: 'reclaim-ee3c6',
    authDomain: 'reclaim-ee3c6.firebaseapp.com',
    storageBucket: 'reclaim-ee3c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESxAfWLPYQytbL5TqqJpOnz1adXNLGnE',
    appId: '1:444912210132:android:5da0f03fb18e28a253eb41',
    messagingSenderId: '444912210132',
    projectId: 'reclaim-ee3c6',
    storageBucket: 'reclaim-ee3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tx4BGq-3dRt2ZVtwPyA9GTHrQeU5HS8',
    appId: '1:444912210132:ios:fc555e1528061faf53eb41',
    messagingSenderId: '444912210132',
    projectId: 'reclaim-ee3c6',
    storageBucket: 'reclaim-ee3c6.appspot.com',
    iosBundleId: 'com.example.reclaim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6tx4BGq-3dRt2ZVtwPyA9GTHrQeU5HS8',
    appId: '1:444912210132:ios:fc555e1528061faf53eb41',
    messagingSenderId: '444912210132',
    projectId: 'reclaim-ee3c6',
    storageBucket: 'reclaim-ee3c6.appspot.com',
    iosBundleId: 'com.example.reclaim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAje2eAHvAmROiYZdWp_snAAuIDn2_WAxQ',
    appId: '1:444912210132:web:54734b16d6c6332f53eb41',
    messagingSenderId: '444912210132',
    projectId: 'reclaim-ee3c6',
    authDomain: 'reclaim-ee3c6.firebaseapp.com',
    storageBucket: 'reclaim-ee3c6.appspot.com',
  );
}
